joi_admin:
    path: joi/admin
    methods: [GET]
    defaults:
        _controller: 'JOI\Controller\Admin\IndexController::indexAction'

joi_admin_product_refresh:
    path: joi/admin/product/refresh
    methods: [ GET ]
    defaults:
        _controller: 'JOI\Controller\Admin\Product\IndexController::refreshAction'

joi_admin_product_refresh_single:
    path: joi/admin/product/refresh/{id_seller}
    methods: [ GET ]
    defaults:
        _controller: 'JOI\Controller\Admin\Product\IndexController::refreshAction'
    requirements:
        id_seller: '\d+'

joi_admin_product_detail:
    path: joi/admin/product/detail
    methods: [ GET ]
    defaults:
        _controller: 'JOI\Controller\Admin\Product\IndexController::detailAction'

joi_admin_seller_refresh:
    path: joi/admin/seller/refresh
    methods: [ GET ]
    defaults:
        _controller: 'JOI\Controller\Admin\Seller\IndexController::refreshAction'

joi_admin_seller_detail:
    path: joi/admin/seller/detail
    methods: [ GET ]
    defaults:
        _controller: 'JOI\Controller\Admin\Seller\IndexController::detailAction'

joi_admin_seller_general_warning:
    path: joi/admin/seller/generalWarning
    methods: [ GET ]
    defaults:
        _controller: 'JOI\Controller\Admin\Seller\IndexController::generalWarningAction'

joi_admin_city_detail:
    path: joi/admin/city/detail
    methods: [ GET, POST ]
    defaults:
        _controller: 'JOI\Controller\Admin\City\IndexController::detailAction'

joi_admin_city_import:
    path: joi/admin/city/import
    methods: [ GET ]
    defaults:
        _controller: 'JOI\Controller\Admin\City\IndexController::importAction'

#AVORTED
#joi_admin_city_activity:
#    path: joi/admin/city/activity/toggle/{id_city}/{state}
#    methods: [ GET ]
#    defaults:
#       _controller: 'JOI\Controller\Admin\City\IndexController::toggleActivityAction'
#    requirements:
#        id_city: '\d+'

joi_admin_city_reset_feature:
    path: joi/admin/city/reset/feature/{step}
    methods: [ GET ]
    defaults:
        _controller: 'JOI\Controller\Admin\City\IndexController::resetFeatureAction'
    requirements:
        step: '\d+'

joi_ajax_city:
    path: joi/ajax/city/search/{step}/{lat}/{long}
    methods: [ GET ]
    defaults:
        _controller: 'JOI\Controller\Ajax\City\IndexController::searchAction'
